import { ToolTipPosition } from '@theme/models/sidebar.model';

export const menuAdmin = [
    {
        matTooltip: 'SIDEBAR.NAV.DASHBOARD.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard'],
        class: 'content-icon-menu py-2',
        icon: 'dashboard',
        title: 'SIDEBAR.NAV.DASHBOARD.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.CALENDAR.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/apps/calendar'],
        class: 'content-icon-menu py-2',
        icon: 'today',
        title: 'SIDEBAR.NAV.CALENDAR.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.CLIENTS.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/clients'],
        class: 'content-icon-menu py-2',
        icon: 'badge',
        title: 'SIDEBAR.NAV.CLIENTS.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.PROJECT.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/projects'],
        class: 'content-icon-menu py-2',
        icon: 'assessment',
        title: 'SIDEBAR.NAV.PROJECT.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.TIMERS.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/timers'],
        class: 'content-icon-menu py-2',
        icon: 'hourglass_empty',
        title: 'SIDEBAR.NAV.TIMERS.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.USERS.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/users'],
        class: 'content-icon-menu py-2',
        icon: 'person',
        title: 'SIDEBAR.NAV.USERS.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.REPORTS.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/reports'],
        class: 'content-icon-menu py-2',
        icon: 'assignment',
        title: 'SIDEBAR.NAV.REPORTS.TITLE',
    },
];

export const menuUser = [
    {
        matTooltip: 'SIDEBAR.NAV.DASHBOARD.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard'],
        class: 'content-icon-menu py-2',
        icon: 'dashboard',
        title: 'SIDEBAR.NAV.DASHBOARD.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.CALENDAR.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/apps/calendar'],
        class: 'content-icon-menu py-2',
        icon: 'today',
        title: 'SIDEBAR.NAV.CALENDAR.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.PROJECT.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/projects'],
        class: 'content-icon-menu py-2',
        icon: 'assessment',
        title: 'SIDEBAR.NAV.PROJECT.TITLE',
    },
    {
        matTooltip: 'SIDEBAR.NAV.TIMERS.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/timers'],
        class: 'content-icon-menu py-2',
        icon: 'hourglass_empty',
        title: 'SIDEBAR.NAV.TIMERS.TITLE',
    },
];

export const menuClient = [
    {
        matTooltip: 'SIDEBAR.NAV.PROJECT.TITLE',
        matTooltipPosition: ToolTipPosition.Right,
        routerLinkActive: 'active',
        routerLink: ['/dashboard/pages/projects'],
        class: 'content-icon-menu py-2',
        icon: 'assessment',
        title: 'SIDEBAR.NAV.PROJECT.TITLE',
    },
];
