// Generated by https://quicktype.io

export interface TopLevel {
  info: Info;
  results: Result[];
}

export interface Info {
  count: number;
  pages: number;
  next: string;
  prev: null;
}

export class Result {
  id: number;
  name: string;
  status: Status;
  species: Species;
  type: string;
  gender: Gender;
  origin: Location | string;
  location: Location | string;
  image: string;
  episode: string[];
  url: string;
  created: string;

  constructor() {
    this.id = 0;
    this.name = '';
    this.status = Status.Unknown;
    this.species = Species.Human;
    this.type = '';
    this.gender = Gender.Unknown;
    this.origin = '';
    this.location = '';
    this.image = '';
    this.episode = [];
    this.url = '';
    this.created = '';
  }
}

export enum Gender {
  Female = 'Female',
  Male = 'Male',
  Unknown = 'unknown',
}

export interface Location {
  name: string;
  url: string;
}

export enum Species {
  Alien = 'Alien',
  Human = 'Human',
}

export enum Status {
  Alive = 'Alive',
  Dead = 'Dead',
  Unknown = 'unknown',
}
