// Generated by https://quicktype.io

import { OrgModel } from './org.model';
import { PhotoURL, UserModel } from './user.model';

// prettier-ignore
export interface ProjectModel {
    _id?:              string;
    color:             string;
    members:           Member[];
    colorAdvance:      ColorAdvance;
    status:            Status;
    advancePercentage: number | null;
    estimatedHours:    number;
    hourCompleted:     number;
    name:              string;
    client:            Client[];
    description:       string;
    org:               OrgModel;
    owner:             UserModel[];
    dueDate?:          null | string;
}

// prettier-ignore
export interface Client {
    _id?:           string;
    color:          string;
    accessProjects: boolean;
    createDate:     string;
    name:           string;
    email:          string;
    org:            string;
    owner:          string;
    __v:            number;
    phone?:         string;
}

export enum ColorAdvance {
    BgDanger = 'bg-danger',
    BgPrimary = 'bg-primary',
    BgWarning = 'bg-warning',
    Empty = '',
    ProgressBarStripedBgDanger = 'progress-bar-striped bg-danger',
}

// prettier-ignore
export interface Member {
    _id?:         string;
    displayName: string;
    photoURL:    PhotoURL;
    userName:    string;
    role:        string;
}

export enum Status {
    Done = 'done',
    Empty = '',
    InProgress = 'inProgress',
    Init = 'init',
}
