// Generated by https://quicktype.io

import { OrgModel } from './org.model';
import { ProjectModel } from './project.model';
import { Type, UserClass } from './user.model';
export interface TasksModel {
    _id?:                  string;
    order:                 number;
    createDate:            string;
    users:                 UserClass[];
    timeEstimated:         number | null;
    createdTimers:         number;
    duration:              number;
    hoursDuration:         HoursDuration[];
    timers:                any[];
    tags:                  string[];
    files:                 File[];
    checklists:            Checklist[];
    comments:              Comment[];
    logs:                  Log[];
    connectGoogleCalendar: boolean;
    taskComplete:          boolean;
    notifications:         any[];
    status:                string;
    name:                  string;
    description:           string;
    project:               ProjectModel;
    owner:                 UserClass;
    org:                   OrgModel;
    dueDate?:              string;
    userMove?:             UserClass;
    previusStatus?:        string;
    idAttachmentCover?:    string;
    idList?:               string;
    previousIdList?:       string;
    previousStatus?:       string;
}
export interface Checklist {
    name:              string;
    id:                number;
    checkItems:        CheckItem[];
    checkItemsChecked: number;
    connectTimers:     boolean;
}
export interface CheckItem {
    name:     string;
    checked:  boolean;
    idTimer?: string;
}
export interface Comment {
    idMember:   string;
    userName:   string;
    imgProfile: File;
    message:    string;
    time:       string;
}
export interface File {
    url?:       string;
    name:       string;
    key?:       string;
    extension?: Extension;
    mimetype?:  Mimetype;
    size?:      number;
    type?:      Type;
    user?:      any;
    color?:     string;
}

export enum Extension {
    JPEG    = 'jpeg',
    PNG     = 'png',
}

export enum Mimetype {
    ImageJPEG   = 'image/jpeg',
    ImagePNG    = 'image/png',
}
export interface HoursDuration {
    name:  HoursDurationName;
    value: number;
}

export enum HoursDurationName {
    Comp = 'comp',
}
export interface Log {
    _id:        string;
    message:    Message;
    userID:     UserClass | string;
    docID:      string;
    orgID:      string;
    dateUpdate: number;
    __v:        number;
}
export interface Message {
    title:   string;
    message: string;
    date:    string;
}
